export const SET_TO_HISTORY = "RATE/SET_TO_HISTORY";
export const SET_FROM_HISTORY = "RATE/SET_FROM_HISTORY";
export const SET_LIST_CURRENCIES = "RATE/SET_LIST_CURRENCIES";
export const SET_CURRENT_DATE = "RATE/SET_CURRENT_DATE";
